spring:
  application:
    name: servicio-greet
server: 
  port: 9000
# Config de el servidor  
eureka: 
  client:    
    serviceUrl:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka
